classDiagram
  class TipoFeira {
    +Long id
    +String nome
    +String descricao
  }

  class Feira {
    +Long id
    +String nome
    +String descricao
    +Boolean ativo
    +TipoFeira tipoFeira
  }

  TipoFeira "1" <-- "0..*" Feira : classifica